[tool.flake8]
application-import-names = "widgets,utils"
import-order-style = "google"
exclude = "venv, .venv, .env, .git, __pycache__"
max-line-length = 79
inline-quotes = "double"
forbidden-imports = "inspect,sys"
disable-noqa = true

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["myproject"]