"""Add user table

Revision ID: 44940fc279c4
Revises: 77062860cfe8
Create Date: 2025-06-08 22:57:57.255560

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44940fc279c4"
down_revision: Union[str, None] = "77062860cfe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("deals_list", sa.String(length=1000), nullable=True),
        sa.Column("notification_list", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Integer(), nullable=True),
        sa.Column("notifications_state", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
