"""Fix relationship error

Revision ID: 6ba48f78cd15
Revises: 840ad921ae56
Create Date: 2025-06-11 00:35:00.035896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba48f78cd15'
down_revision: Union[str, None] = '840ad921ae56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deals', 'users', ['user_id'], ['id'])
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'user_id')
    # ### end Alembic commands ###
