"""Fix Deals column name and default state

Revision ID: 84d489e4bad1
Revises: 9f7ea7a83e13
Create Date: 2025-08-02 18:30:06.889229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84d489e4bad1"
down_revision: Union[str, None] = "9f7ea7a83e13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deals", sa.Column("is_done", sa.Boolean(), nullable=False))
    op.drop_column("deals", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deals",
        sa.Column(
            "is_active", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("deals", "is_done")
    # ### end Alembic commands ###
